## 这是一个标题
**加粗这些文字**

[This is a link](https://chatgpt.com/c/6725fa7c-8988-8003-adfb-20f5de41016d)

这是一个数学公式（单独占一行）: $$x^2 + y^4 = 1$$

这是另一个公式（同一行）: $y = ax + b$  
加 $x + y$  
减 $x - y$  
乘 $x \times y$  
除 $x \div y$
$$x^3$$ 
$$H_2O$$
$$S_{input}$$
$$\sum(x^2 + y^2)$$
$$\sqrt[3]x$$
$$\sqrt[3]{a^2}$$
$$\sqrt[3]a^2m^2$$
$$\sqrt[3]{a^2m^2}$$
$$\frac{x+y}{x-y}$$

# 1**fett**
## 2*grtg*
### 3~~wefkheruifi~~
#### 4
##### 5
###### 6
- 我是列表第一项
- 我是列表第二项
- 我是列表第三项
1. first
2. second
3. third
![Los Angeles](https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Los_Angeles_with_Mount_Baldy.jpg/1920px-Los_Angeles_with_Mount_Baldy.jpg)

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array(["Hello", True, 3.14])

array(['Hello', 'True', '3.14'], dtype='<U32')

#### ndim可以传出数组的维度

In [7]:
print(arr1.ndim)
print(arr2.ndim)

1
2


#### shape返回各个维度的元素的个数

In [8]:
print(arr2.shape)
print(arr2.shape)

(2, 3)
(2, 3)


#### 创建元素为数字序列的数组
##### (起始值，结束值，步长)

In [11]:
np.arange(5, 10, 2)

array([5, 7, 9])